const combatTrackerConfig = {
    turnMarker: {
        enabled: false,
    },
    resource: "",
    skipDefeated: true,
};

const permissions = {
    BROADCAST_AUDIO: [2, 3, 4],
    BROADCAST_VIDEO: [2, 3, 4],
    TOKEN_CONFIGURE: [2, 3, 4],
    ACTOR_CREATE: [3, 4],
    PLAYLIST_CREATE: [3, 4],
    CARDS_CREATE: [3, 4],
    ITEM_CREATE: [1, 2, 3, 4],
    JOURNAL_CREATE: [2, 3, 4],
    NOTE_CREATE: [2, 3, 4],
    REGION_CREATE: [1, 2, 3, 4],
    TOKEN_CREATE: [3, 4],
    TOKEN_DELETE: [3, 4],
    SHOW_CURSOR: [],
    SHOW_RULER: [1, 2, 3, 4],
    MANUAL_ROLLS: [2, 3, 4],
    SETTINGS_MODIFY: [3, 4],
    MACRO_SCRIPT: [1, 2, 3, 4],
    WALL_DOORS: [2, 3, 4],
    PING_CANVAS: [1, 2, 3, 4],
    QUERY_USER: [1, 2, 3, 4],
    FILES_UPLOAD: [1, 2, 3, 4],
    DRAWING_CREATE: [1, 2, 3, 4],
    FILES_BROWSE: [1, 2, 3, 4],
    MESSAGE_WHISPER: [2, 3, 4],
};

const prototypeTokenOverrides = {
    base: {
        sight: {},
        ring: {},
        lockRotation: true,
        turnMarker: {},
    },
    army: {
        sight: {},
        ring: {},
        turnMarker: {},
    },
    familiar: {
        displayName: 30,
        displayBars: 30,
        sight: {
            enabled: true,
        },
        ring: {},
        turnMarker: {},
    },
    hazard: {
        sight: {},
        ring: {},
        turnMarker: {},
    },
    loot: {
        sight: {},
        ring: {},
        turnMarker: {},
    },
    party: {
        sight: {},
        ring: {},
        turnMarker: {},
    },
    vehicle: {
        displayName: 0,
        displayBars: 0,
        sight: {
            enabled: true,
        },
        ring: {},
        turnMarker: {},
    },
    character: {
        displayName: 30,
        displayBars: 30,
        sight: {
            enabled: true,
        },
        ring: {},
        turnMarker: {},
    },
    npc: {
        displayName: 20,
        displayBars: 20,
        sight: {
            enabled: true,
        },
        ring: {},
        turnMarker: {},
    },
};

const healthStatusData = {
    dead: "Dead",
    enabled: true,
    full: "Perfectly Fine",
    entries: [
        { label: "At Death's Door", marker: 1 },
        { label: "Not Feeling Good", marker: 25 },
        { label: "Seen Better Days", marker: 50 },
        { label: "Barely Hurt", marker: 75 },
    ],
};

const worldSettings = {
    core: {
        animateRollTable: false,
        combatTrackerConfig,
        permissions,
        prototypeTokenOverrides,
        tokenAutoRotate: false,
        tokenDragPreview: false,
    },
    system: {
        "automation.actorsDeadAtZero": true,
        "automation.encumbrance": true,
        critRule: "doubledice",
        metagame_showDC: false,
        metagame_showResults: true,
        metagame_showBreakdowns: false,
        metagame_secretDamage: true,
        metagame_secretCondition: true,
        metagame_partyVision: false,
        metagame_showPartyStats: true,
        metagame_tokenSetsNameVisibility: true,
        metagame_secretChecks: false,
        minimumRulesUI: 1,
        statusEffectShowCombatMessage: true,
        "homebrew.languages": [{ value: "ancifor", id: "ancifor" }],
        "homebrew.featTraits": [{ value: "duckmancy", id: "duckmancy" }],
        "homebrew.weaponTraits": [{ value: "duckmancy", id: "duckmancy" }],
        "homebrew.shieldTraits": [{ value: "duckmancy", id: "duckmancy" }],
        "homebrew.equipmentTraits": [{ value: "duckmancy", id: "duckmancy" }],
    },
    "pf2e-hud": {
        healthStatusData,
        "tracker.started": false,
        "tracker.partyAsObserved": true,
    },
    "pf2e-toolbelt": {
        "actionable.action": true,
        "actionable.cast": true,
        "actionable.item": false,
        "actionable.physical": false,
        "actionable.spell": false,
        "anonymous.action": true,
        "anonymous.spell": true,
        "anonymous.traits": "blacklist",
        "arp.enabled": true,
        "arp.force": true,
        "arp.price": true,
        "arp.shield": true,
        "autoCover.creature": "cross",
        "autoCover.dead": true,
        "autoCover.prone": true,
        "autoCover.wall": "center-center",
        "betterSheet.partyAsObserved": true,
        "betterInventory.coins": true,
        "betterInventory.dropped": true,
        "droppeth.enabled": true,
        "droppeth.light": true,
        "giveth.effect": "ally",
        "identify.delay": true,
        "identify.enabled": true,
        "identify.identifyPartials": true,
        "identify.playerRequest": true,
        "resourceTracker.enabled": true,
        "rollTracker.enabled": true,
        "unided.create": true,
        "unided.update": true,
        "targetHelper.enabled": true,
        "underground.enabled": true,
        "underground.tiles": false,
    },
    "xdy-pf2e-workbench": {
        heroPointRules: "keeleysHeroPointRule",
        enableAutomaticMove: "reaching0HP",
        autoReduceStunned: true,
        giveUnconsciousIfDyingRemovedAt0HP: true,
        autoRemoveUnconsciousAtGreaterThanZeroHP: true,
        giveWoundedWhenDyingRemoved: true,
        autoGainDyingAtZeroHP: "addWoundedLevelForCharacters",
        autoGainDyingAtZeroHPIfCriticallyHitOneMore: "addForCharacters",
        autoGainDyingIfTakingDamageWhenAlreadyDying: "addForCharacters",
        autoRemoveDyingAtGreaterThanZeroHP: "removeForCharacters",
        dropHeldItemsOnBecomingUnconscious: true,
        sheatheHeldItemsAfterEncounter: true,
        sheatheHeldItemsAfterEncounterTypes: "weapon",
    },
};

export { worldSettings };
